#
###################################
# Site wide configuration
####################################
#
title: SaltyWendigo
email: cgutshal@gmail.com
description: A simple and awesome blog theme powered by jekyll.
# the base hostname & protocol for your site
# If your project is placed in https://github.com/cgutshal/cgutshal.github.io at master branch
# Then, the 'url' is: http://cgutshal.github.io
# If your project is placed in another repository as a gh-pages branch, like: https://github.com/cgutshal/projectname
# Then, the 'url' is: http://cgutshal.github.io/projectname
url:

#
###################################
# Jekyll configuration
####################################
#
markdown: kramdown
highlighter:  pygments
excerpt_separator: <!--more-->

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false

#
###################################
# Site Owner configuration
####################################
#
owner:
  name: SaltyWendigo
  avatar: avatar.jpg
  #job: "Infanstructure Engineer"
  bio: King of the Thunderlizards. Knowledge (Computers) +3. Enjoys Table and Video based games.
  email: cgutshal@gmail.com
  disqus-shortname:
  twitter: cgutshal
  facebook: #cgutshal
  google:
    plus: cgutshal
    analytics:
    verify:
    ad-client:
    ad-slot:
  bing-verify:
  github: cgutshal
  stackoverflow: #123456/cgutshal   from a "http://stackoverflow.com/users/123456/cgutshal" link
  linkedin: #cgutshal
  xing: #cgutshal
  instagram: cgutshal
  lastfm: #cgutshal
  tumblr: #cgutshal
  pinterest: #cgutshal
  foursquare: #cgutshal
  steam: #cgutshal
  dribbble: #cgutshal
  youtube: #cgutshal
  soundcloud: #cgutshal
  weibo: #cgutshal
  flickr: #cgutshal
  codepen: #cgutshal
